name: Publish Docker image

on:
       push:
            branches: ['capstone']
       pull_request:
            branches: ['capstone']

jobs:
        npm-jobs:

            runs-on: ubuntu-latest

            steps:
                - uses: actions/checkout@v2
                
                - uses: actions/setup-node@v3
                     with:
                     node-version: 16
                     cache: 'npm'
                     cache-dependency-path: capstone_project/hello-world/package-lock.json
                     
                - run: npm install
                     working-directory: capstone_project/hello-world/src
                - run: npm test
                     working-directory: capstone_project/hello-world/src
                 
        docker-jobs:

            needs: [npm-jobs]
            runs-on: ubuntu-latest

            steps:
                - uses: actions/checkout@v2

                - name: Build container
                  working-directory: capstone_project/hello-world/
                  run: docker compose up -d
