name: Publish Docker image

on:
       push:
            branches: [ "capstone" ]
       pull_request:
            branches: [ "capstone" ]

jobs:
        npm-jobs:
            #Npm actions will be executed as first job  
            runs-on: ubuntu-latest

            steps:
                - uses: actions/checkout@v2

                - name: NPM dependencies
                  working-directory: capstone_project/hello-world/
                  run: npm install

                - name: NPM testing 
                  working-directory: capstone_project/hello-world/
                  run: npm test
                  
        docker-jobs:

            #If the test above is  success, docker actions will be executed
            needs: [npm-jobs]
            runs-on: ubuntu-latest

            steps:
                - uses: actions/checkout@v2

                - name: Build container
                  working-directory: capstone_project/hello-world/
                  run: docker compose up -d
