name: Publish Docker image

on:
  push:
    branches: ['capstone']
  pull_request:
    branches: ['capstone']

jobs:

  job1:

    name: npm install and test
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: capstone_project/hello-world/package-lock.json
      - run: npm install
        working-directory: capstone_project/hello-world/
      - run: npm test
        working-directory: capstone_project/hello-world/
        
  job2:
      name: Build and Push Docker Image
      needs: [job1]
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: capstone/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
