name: Publish Docker image

on:
  push:
    branches: ['capstone']
  pull_request:
    branches: ['capstone']

jobs:
  build: 

    runs-on: ubuntu-latest
    
    #citing actions / setup-node
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm test

