name: Publish Docker image

on:
       push:
            branches: [ "capstone" ]
       pull_request:
            branches: [ "capstone" ]

jobs:
        npm-jobs:

            runs-on: ubuntu-latest
            strategy:
              matrix:
                node-version: [12]
            steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: NPM dependencies 
              working-directory: capstone_project/hello-world/
              run: npm install
            - name: NPM testing 
              working-directory: capstone_project/hello-world/
              run: npm test
                  
        docker-jobs:

            #needs: [npm-jobs]
            runs-on: ubuntu-latest

            steps:
                - uses: actions/checkout@v2

                - name: Build container
                  working-directory: capstone_project/hello-world/
                  run: docker compose up -d
