name: Publish Docker image

on:
       push:
            branches: [ "main" ]
       pull_request:
            branches: [ "main" ]

jobs:
        npm-jobs:

            runs-on: ubuntu-latest

            steps:
                - uses: actions/checkout@v2
                
                - name: NPM dependencies 
                  working-directory: capstone_project/hello-world/src
                  run: npm install
                - name: NPM testing 
                  working-directory: capstone_project/hello-world/src
                  run: npm test
                  
        docker-jobs:

            needs: [npm-jobs]
            runs-on: ubuntu-latest

            steps:
                - uses: actions/checkout@v2

                - name: Build container
                  working-directory: capstone_project/hello-world/
                  run: docker compose up -d
